sudo: required
services:
  - docker

before_install:
  - docker build -t <%= username %>/<%= projectName %> -f Dockerfile.dev .

script:
  - docker run <%= username %>/<%= projectName %> yarn test:coverage
